use_default_settings: true
server:
  secret_key: "weknora_searxng_secret_key_change_me"
  limiter: false
  image_proxy: true
search:
  safe_search: 0
  autocomplete: ""
  default_lang: "fr"
  formats:
    - html
    - json
